# These are supported funding model platforms

github: kabahandle # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
#patreon: kabahandle # Replace with a single Patreon username
#open_collective: kabahandle # Replace with a single Open Collective username
#ko_fi: kabahandle # Replace with a single Ko-fi username
#tidelift: kabahandle # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
#community_bridge: kabahandle # Replace with a single Community Bridge project-name e.g., cloud-foundry
#liberapay: kabahandle # Replace with a single Liberapay username
#issuehunt: kabahandle # Replace with a single IssueHunt username
#otechie: kabahandle # Replace with a single Otechie username
custom: "https://github.com/sponsors/kabahandle" # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
